# -*- coding: utf-8 -*-
"""BLCH9X2_Assignment1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BU6R-nk3_nPX5t6AkvPvvVmF8xCVeb6p

216038155 Phenyo Thato Molete
Cryptographic Hash Lab
Block Chain ASSIGNMENT1
4/8/2026
"""

import hashlib
import time

def sha256_string(s):
    return hashlib.sha256(s.encode("utf-8")).hexdigest()

#Testing
if __name__ == "__main__":
    print(sha256_string("PhenyoMFE"))
    print(sha256_string("phenyomfe"))
    print(sha256_string("IamsuperHungry"))
    print(sha256_string("IAMSUPERhungry"))

def sha256_file(file_path):
    h = hashlib.sha256()
    with open(file_path, "rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            h.update(chunk)
    return h.hexdigest()

"""Before changing a comma placement in the file"""

my_hash = sha256_file("/content/BLOCKCHAINASSIGNMENTDOC.rtf")
print(my_hash)

"""After changing a comma placement in the file :)"""

my_hash = sha256_file("/content/BLOCKCHAINASSIGNMENTDOC.rtf")
print(my_hash)

def avalanche_demo(s):
    digest_original = hashlib.sha256(s.encode("utf-8")).hexdigest()
    mutated_s = s[:-1] + chr(ord(s[-1]) ^ 1) if s else "a"
    digest_mutated = hashlib.sha256(mutated_s.encode("utf-8")).hexdigest()
    return (digest_original, digest_mutated)

def bit_difference(hex1, hex2):
    int1 = int(hex1, 16)
    int2 = int(hex2, 16)
    xor_result = int1 ^ int2
    return bin(xor_result).count("1")

if __name__ == "__main__":
    orig, mut = avalanche_demo("PhenyoMFE")
    diff_bits = bit_difference(orig, mut)
    percent = (diff_bits / 256) * 100
    print("Original:", orig)
    print("Mutated: ", mut)
    print("Identical?", orig == mut)
    print(f"Bits different: {diff_bits}/256 ({percent:.2f}%)")

if __name__ == "__main__":
    print(sha256_string("hello"))
    print(sha256_file("/content/BLOCKCHAINASSIGNMENTDOC.rtf"))

    orig, mut = avalanche_demo("IamsuperHungry")
    diff_bits = bit_difference(orig, mut)
    percent = (diff_bits / 256) * 100
    print("Original:", orig)
    print("Mutated: ", mut)
    print("Identical?", orig == mut)  #True or false
    print(f"Bits different: {diff_bits}/256 ({percent:.2f}%)")

def proof_of_work(message, n):
    target_prefix = "0" * n
    nonce = 0
    start_time = time.perf_counter()

    while True:
        candidate = f"{message}{nonce}"
        digest = hashlib.sha256(candidate.encode("utf-8")).hexdigest()

        if digest.startswith(target_prefix):
            elapsed_seconds = time.perf_counter() - start_time
            return {
                "nonce": nonce,
                "digest": digest,
                "attempts": nonce + 1,
                "seconds": elapsed_seconds
            }

        nonce += 1

result3 = proof_of_work("PhenyoMFE", 3)
print(result3)

result4 = proof_of_work("PhenyoMFE", 4)
print(result4)